layout_spectrum: 0.4355532
color:
  saturation: 0.1895811
  lightness: 0.4297122
  brandStrength: 0.8125672
  brandColors:
    - '#FFFFFF'
    - '#6C1F85'
    - '#DBA7EF'
    - '#8F4BA4'
    - '#6F5378'
  rhythmicContrast: 0.6288937
typography_spectrum: 0.7610097
name: ZenQuary
